EMPLOYEES_COLLECTION = "employees"
ATTENDANCE_COLLECTION = "attendance"

API_PREFIX = "/api"
EMPLOYEES_ROUTE_PREFIX = f"{API_PREFIX}/employees"
ATTENDANCE_ROUTE_PREFIX = f"{API_PREFIX}/attendance"

DEFAULT_CORS_ORIGINS = "http://localhost:5173,http://localhost:3000"

EMPLOYEE_ID_PREFIX = "EMP"
EMPLOYEE_ID_PAD_WIDTH = 3
